### ISSUE TITLE
When the filename incluing a space, the plugin will fail.

### ISSUE THREAD

**Issue by databill** [Rykka/InstantRst#14]
Two files have the same contents and in the same directory.

```Bash
julien:rst julien$ ls /tmp/*.rst
/tmp/b.rst   /tmp/c c.rst
```
* When VI open file *b.rst*, :instantRst command works fine.
* When VI open file *c c.rst*, :instantRst command wont open a tab in web browser, and you can view nothing even you open a tab for localhost:5676 manually. While you open another file and call :instantRst correctly, the file with spaces in the filename can also have a live view in the browser.

**Comment by Rykka** [comment]
you are working under linux or mac?

**Comment by databill** [comment]
I'm working in OSX.

I submit a patch, https://github.com/databill/InstantRst/commit/d2dd7df050a03b3d208205d9aa340cce024f00f9

**Comment by Rykka** [comment]
fine，you can submit a pull request, if it's ok on your machine.

**Comment by databill** [comment]
Hi Rykka, it's done.
