### ISSUE TITLE
Give error message if starting server fails

### ISSUE THREAD

**Issue by swenzel** [Rykka/InstantRst#7]
Hi there,

I tried your plugin today and once I set up everything, it works fine.
However before I got there it told me that the server is ready at http://localhost:5676 although it obviously was not.
In fact instant-rst.py was not installed at all and even after I installed it I had the same problem until I noticed that I forgot to add the executable to the path variable.
Dunno how exactly your code works but maybe you could include some check like 'which instantRst' to make sure it is actually accessible and give an error message if it's not? Would've saved me some time figuring out where the problem is.

Greetings
Swen

**Comment by rbjorklin** [comment]
I just encountered this behavior and it's very confusing when vim gives the impression that a socket was successfully opened and then nothing happens.

My error turned out to be that I had installed InstantRst with python 3 which it doesn't seem to be compatible with.
